# Generated by Django 4.0.2 on 2022-02-10 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='myuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('Email', models.EmailField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('confirm_password', models.CharField(max_length=20, null=True)),
                ('phone_number', models.CharField(max_length=11)),
                ('profile_picture', models.ImageField(default='images/images.jpeg', upload_to='images/')),
                ('is_active', models.BooleanField(default=False)),
                ('country', models.CharField(max_length=20, null=True)),
                ('birthdate', models.DateField(null=True)),
                ('fb_account', models.URLField(null=True)),
            ],
        ),
    ]
